version: '3'

services:
  frontend:
    container_name: frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always

  backend:
    container_name: backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/db:/data/db
    restart: always
